### ISSUE TITLE
Sync Video to audio button

### ISSUE THREAD

**Issue by danya-gharbieh** [Trekky12/kburns-slideshow#14]
Hi,

in my slideshow i added around 5 pictures and a long music ( with duration 00:02:22) so when i tried to use sync video to audio button, below error generated :

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\user\Documents\application\kburns\gui\app.py", line 1163, in syncToAudio
    self.sm.adjustDurationsFromAudio()
  File "C:\Users\user\Documents\application\kburns\slideshow\SlideManager.py", line 693, in adjustDurationsFromAudio
    timestamps = self.getTimestampsFromAudio()
  File "C:\Users\user\Documents\application\kburns\slideshow\SlideManager.py", line 681, in getTimestampsFromAudio
    timestamps = timestamps + [float(timestamp) + offset for timestamp in track.getTimestamps(self.config["aubio"])]
  File "C:\Users\user\Documents\application\kburns\slideshow\AudioFile.py", line 17, in getTimestamps
    timestamps = subprocess.check_output(["%s" % (aubio), "-i", self.file, "-O", "kl"],
  File "C:\Program Files\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\user\\Documents\\aubio-0.4.6-win64-ffmpeg\\bin\\aubioonset.exe', '-i', 'C:/Users/user/Desktop/music.mp3', '-O', 'kl']' returned non-zero exit status 3221225781. 

btw i'm using python 3.10
any idea ?

**Comment by Trekky12** [comment]
Could you call `aubioonset` directly from the command line and show the output?
E.g.
```
C:\Users\user\Documents\aubio-0.4.6-win64-ffmpeg\bin\aubioonset.exe -i 'C:/Users/user/Desktop/music.mp3' -O kl
```
